app/unity/views.py
from flask import (Blueprint, render_template, flash, request,
                   redirect, url_for)
from jinja2 import TemplateNotFound
from app.models import Unity, User, Comment
from app.forms import UnityForm, CommentForm
from app.constants import DATE_TIME_NOW
from app.utils import makeSlug
from flask.ext.login import login_required, current_user
from flask.ext.mongoengine import Pagination

mod = Blueprint('unity', __name__, url_prefix='/unity')


@mod.route('/', defaults={'tag': None, 'user': None, 'pageNum': 1})
@mod.route('/blog', defaults={'tag': None, 'user': None, 'pageNum': 1})
@mod.route('/listposts', defaults={'tag': None, 'user': None, 'pageNum': 1})
@mod.route('/listposts/page/<int:pageNum>',
           defaults={'tag': None, 'user': None})
@mod.route('/listposts/tag/<tag>', defaults={'user': None, 'pageNum': 1})
@mod.route('/listposts/tag/<tag>/page/<int:pageNum>', defaults={'user': None})
@mod.route('/listposts/user/<user>', defaults={'tag': None, 'pageNum': 1})
@mod.route('/listposts/user/<user>/page/<int:pageNum>', defaults={'tag': None})
def listUnity(tag, user, pageNum):
    if tag:
        unitySet = Pagination(
            Unity.get_set(postType='blog', tags=tag),
            pageNum, 10)
        pageTitle = tag
    if user:
        user = User.get(email=user)
        unitySet = Pagination(
            Unity.get_set(postType='blog', author=user),
            pageNum, 10)
        pageTitle = user.email
    elif not tag and not user:
        unitySet = Pagination(
            Unity.get_set(postType='blog'),
            pageNum, 10)
        pageTitle = "blog"  # "listUnity"
    return render_template('unity/listUnity.html',
                           pageTitle=pageTitle,
                           unitySet=unitySet,
                           page=pageNum)


@mod.route('/newunity', methods=['GET', 'POST'])
@login_required
def newUnity():
    form = UnityForm()

    if request.method == 'POST':
        if not form.validate_with_slug():
            return render_template("unity/newUnity.html",
                                   form=form,
                                   pageTitle="newUnity")
        else:
            slug = makeSlug(form.title.data)
            newUnity = Unity(title=form.title.data,
                             slug=slug,
                             body=form.body.data,
                             postType=form.postType.data)
            if form.tags.data:
                newUnity.tags = form.tags.data
            if form.source.data:
                newUnity.source = form.source.data
            if form.summary.data:
                newUnity.summary = form.summary.data
            newUnity.author = User.get(email=current_user.email)
            newUnity.save()
            flash('Your unity has been posted.')
            return redirect(url_for('.staticUnity', slug=slug))
    elif request.method == 'GET':
        return render_template("unity/newUnity.html",
                               form=form,
                               pageTitle="newUnity")


@mod.route('/<slug>/edit', methods=['GET', 'POST'])
@login_required
def editUnity(slug):
    unity = Unity.get(slug=slug)
    slug = unity.slug
    form = UnityForm(obj=unity)

    if request.method == 'POST':
        if not form.validate_on_update(slug):
            return render_template('unity/newUnity.html',
                                   pageTitle=unity.title,
                                   slug=slug,
                                   form=form)
        else:
            form.populate_obj(unity)
            unity.edited_on.append(DATE_TIME_NOW)
            unity.save()
            flash("Your page has been updated.")
            return redirect(url_for('.staticUnity', slug=slug))
    elif request.method == 'GET':
        form.populate_obj(unity)
        return render_template('unity/newUnity.html',
                               pageTitle=unity.title,
                               slug=slug,
                               form=form)


@mod.route('/<slug>', methods=['GET', 'POST'])
def staticUnity(slug):
    if request.method == 'POST':
        unity = Unity.get_or_404(slug=slug)
        form = CommentForm()
        if not form.validate():
            return render_template('unity/staticUnity.html',
                                   pageTitle=unity.title,
                                   unity=unity,
                                   form=form)
        else:
            newComment = Comment(body=form.comment.data)
            newComment.author = User.get(email=current_user.email)
            unity.comments.append(newComment)
            unity.save()
            form.comment.data = None  # resets field on refresh
            flash('Comment Posted')
        return render_template('unity/staticUnity.html',
                               pageTitle=unity.title,
                               unity=unity,
                               form=form)
    elif request.method == 'GET':
        try:
            return render_template('unity/%s.html' % slug,
                                   pageTitle=slug)
        except TemplateNotFound:
            unity = Unity.get_or_404(slug=slug)
            currentUser = User.get(email=current_user.email)
            if (unity.postType == 'draft' and
                    unity.author != currentUser and
                    currentUser.is_admin() is False):
                flash('You must be draft author or admin to view.')
                return redirect(url_for('.listUnity'))
            else:
                form = CommentForm()
                return render_template('unity/staticUnity.html',
                                       pageTitle=unity.title,
                                       unity=unity,
                                       form=form)

app/users/views.py
from flask import (Blueprint, render_template, url_for, request,
                   redirect, flash, g, abort, session)
from app import lm
from app.forms import (LoginForm, RegisterUser,
                       ForgotPasswordForm, ResetPasswordForm)
from app.models import (User)
from flask.ext.login import (login_user, logout_user,
                             current_user, login_required)
from app.constants import DATE_TIME_NOW
from app.emails import email_confirmation, email_password_reset
from app.decorators import anon_required


mod = Blueprint('users', __name__, url_prefix='/users')


@lm.user_loader
def load_user(id):
    user = User.get(email=id)
    return user


@mod.before_request
def before_request():
    g.user = current_user


@mod.route('/login', methods=['GET', 'POST'])
@anon_required
def login():
    form = LoginForm()
    pageTitle = "login"

    if request.method == 'POST':
        if form.validate() is False:
            return render_template('users/login.html',
                                   form=form,
                                   pageTitle=pageTitle)
        else:
            # user = User.get(email=form.email.data.lower().strip())
            user = User.get(email=form.email.data.lower().strip())
            if user and user.roles.can_login is True:
                #add remember_me
                user.last_seen = DATE_TIME_NOW
                user.save()
                login_user(user)
                return redirect(request.args.get('next') or
                                url_for('.profile',
                                        user_id=user.get_id())
                                )
            else:
                flash("Please confirm your email address.")
                return render_template('users/login.html',
                                       form=form,
                                       pageTitle=pageTitle)
    elif request.method == 'GET':
        if request.args.get('next'):
            session['next'] = (request.args.get('next') or
                               request.referrer or None)
        return render_template('users/login.html',
                               form=form,
                               pageTitle=pageTitle)


def after_login(resp):
    pass


@mod.route('/logout')
@login_required
def logout():
    logout_user()
    if session.get('credentials'):
        if redirect(url_for('.googleDisconnect')):
            flash("Successfully disconnected from Google.")
    flash("Successfully logged out.")
    session.clear()
    return redirect(url_for('index'))


@mod.route('/register', methods=['GET', 'POST'])
@anon_required
def register():
    form = RegisterUser()
    pageTitle = "register"

    if request.method == 'POST':
        if form.validate() is False:
            return render_template('users/register.html',
                                   form=form,
                                   pageTitle=pageTitle)
        else:
            newUser = User(firstname=form.firstname.data.title(),
                           lastname=form.lastname.data.title(),
                           email=form.email.data.lower().strip())
            newUser.set_password(form.password.data)
            newUser.save()
            payload = User.get_activation_link(newUser)
            email_confirmation(newUser, payload)
            flash("Please confirm your email address by cheking your email.")
            return redirect(url_for('index'))

    elif request.method == 'GET':
        return render_template('users/register.html',
                               form=form,
                               pageTitle=pageTitle)

    # flash("This feature is currently disabled.")
    # return redirect(url_for('index'))


@mod.route('/activate/<payload>')
@anon_required
def activateUser(payload):
    user_email = User.check_activation_link(payload)
    if not user_email:
        return abort(404)
    user = User.get(email=user_email)
    if user:
        if user.confirmed is None:
            user.activate_user()
            user.save()
            flash('Your account has been activated.')
        else:
            flash('Your account was already active.')
        return redirect(url_for('.login'))
    else:
        return abort(404)


@mod.route('/forgotpassword', methods=['GET', 'POST'])
@anon_required
def forgotPassword():
    form = ForgotPasswordForm()
    pageTitle = "forgot password"

    if request.method == 'POST':
        if not form.validate():
            return render_template('users/forgotPassword.html',
                                   form=form,
                                   pageTitle=pageTitle)
        else:
            try:
                user = User.get(email=form.email.data.lower().strip())
            except:
                flash("That email does not exist, please try another.")
                return render_template('users/forgotPassword.html',
                                       form=form,
                                       pageTitle=pageTitle)

            # # disallows password reset link to be reused
            # oldhash = user.pwdhash[:10]
            # payload = User.get_password_reset_link(user) + oldhash

            payload = User.get_password_reset_link(user)
            email_password_reset(user, payload)

            flash("Password reset email has been sent. \
                   Link is good for 24 hours.")
            return redirect(url_for('index'))
    elif request.method == 'GET':
        return render_template('users/forgotPassword.html',
                               form=form,
                               pageTitle="Forgot Password")


@mod.route('/resetpassword/<payload>', methods=['GET', 'POST'])
@anon_required
def reset_password(payload):
    form = ResetPasswordForm()
    pageTitle = "reset password"

    # disallows password reset link to be reused
    unhashed_payload = User.check_password_reset_link(payload)
    user_email = unhashed_payload[0]
    oldhash = unhashed_payload[1]

    if user_email:
        user_oldhash = User.get(email=user_email).pwdhash[:10]
        if oldhash != user_oldhash:
            flash("Token has been used previously.  Please try again.")
            return redirect(url_for('.forgotPassword'))

    if not user_email:
        flash("Token incorrect or has expired.  Please try again.")
        return redirect(url_for('.forgotPassword'))

    if request.method == 'POST':
        if not form.validate():
            return render_template('users/resetPassword.html',
                                   form=form,
                                   pageTitle=pageTitle)
        else:
            user = User.get(email=user_email)
            user.set_password(form.password.data)
            user.save()
            #email password reset
            flash("Password has been reset, please login")
            return redirect(url_for('.login'))
    elif request.method == 'GET':
        return render_template('users/resetPassword.html',
                               form=form,
                               pageTitle=pageTitle)


@mod.route('/profile/<user_id>')
def profile(user_id):
    user = User.get(email=user_id)
    return render_template('users/profile.html',
                           user=user,
                           pageTitle=user_id)

app/templates/unity/about.html
<!-- extends base.html -->
{% extends "base.html" %}

{% block content %}
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec justo massa, condimentum a rutrum a, sollicitudin ut quam. Phasellus dictum velit vel lorem feugiat fringilla. Aliquam erat volutpat. Sed eu ligula neque. Vestibulum condimentum lobortis nisl ut pharetra. Fusce facilisis elit ut nibh tristique at dictum turpis bibendum. Proin luctus porttitor pretium. Etiam vitae nulla urna, luctus iaculis magna. Curabitur nunc augue, accumsan sed suscipit et, viverra congue sem. Phasellus interdum magna eu mi euismod pretium. Quisque in vestibulum tortor. Aenean laoreet est sed purus ultrices feugiat. Maecenas dui nunc, tincidunt ut mollis quis, mollis nec lorem. Curabitur in mauris ante. Nunc iaculis posuere arcu eget luctus. Aenean pulvinar facilisis arcu, quis egestas nulla venenatis in. Pellentesque vitae luctus nulla. Duis quam libero, interdum egestas pharetra vel, tempor nec turpis. Sed mauris tortor, auctor ut ultricies sed, lacinia quis mi.
        </p>
{% endblock %}

app/templates/unity/battleship.html
<!-- extends base.html -->
{% extends "base.html" %}

{% block head %}
    <script src="http://www.google.com/jsapi" type="text/javascript"></script>
    <script type="text/javascript">google.load("jquery", "2.3.2");</script>
    <script src="http://d3lp1msu2r81bx.cloudfront.net/kjs/js/lib/kinetic-v4.5.4.js"></script>
    <script defer="defer" src="{{ url_for('static', filename='js/battleship.js') }}"></script>
    <link rel="stylesheet/less" type="text/css" href="{{ url_for('static', filename='css/style.less') }}" />
    <link rel="stylesheet/less" type="text/css" href="{{ url_for('static', filename='css/battleship.less') }}" />
    <script src="{{ url_for('static', filename='js/less-1.4.1.min.js') }}" type="text/javascript"></script>
{% endblock %}
{% block content %}
        <div id="container">
            <div id="boardContainer"></div>
            <div id="messages">
                <ul>
                    <li></li>
                    <li></li>
                    <li></li>
                </ul>
            </div>
        </div>
{% endblock %}

app/templates/unity/contact.html
<!-- extends base.html -->
{% extends "base.html" %}

{% block content %}
<table id="contactinfo" class="tableSmallCaps">
    <tr>
	<th>phone</th><td><a href="callto://3123610322">312.361.0322</a></td>
    </tr>
    <tr>
	<th>email</th><td><script src="{{ url_for('static', filename='js/email.js') }}"></script></td>
    </tr>
    <tr>
	<th>twitter</th><td><a href="http://twitter.com/jerknextdoor">@jerknextdoor</a></td>
    </tr>
    <tr>
	<th>skype</th><td><a href="callto://cldershem">cldershem</a></td>
    </tr>
    <tr>
	<th>last.fm</th><td><a href="http://last.fm/user/cldershem">cldershem</a></td>
    </tr>
    <tr>
	<th>google+</th><td><a href="http://google.com/+CameronDershem">cldershem</a></td>
    </tr>
    <tr>
	<th>github</th><td><a href="http://github.com/cldershem">cldershem</a></td>
    </tr>
</table>
{% endblock %}

app/templates/unity/dev.html
<!-- extends base.html -->
{% extends "base.html" %}

{% block content %}
<table id="dev" class="tableSmallCaps">
	<tr>
		<th><a href="http://homelessgaffer.com/wikitest/tikiwiki">wiki</a></th><td>wiki about bicycle tour</td>
	</tr>
	<tr>
		<th><a href="{{ url_for('unity.staticUnity', slug='battleship') }}">battleshipweb</a></th><td>first non-tiny python game being converted into a webapp.</td>
	</tr>
	<tr>
        <th>genealogy</th><td>million dollar idea</td>
	</tr>
	<tr>
		<th>firstkisses</th><td>first kisses project</td>
	</tr>
	<tr>
		<th>homelessgaffer.com</th><td>The CMS that powers this website.</td>
	</tr>
</table>
{% endblock %}

app/templates/unity/food.html
<!-- extends base.html -->
{% extends "base.html" %}

{% block content %}
    {% for post in posts %}
        <h2><a href="{{ url_for('singlePost', slug=post.slug) }}">{{ post.title }}</a></h2>
        <p>{{ post.body|truncate(100) }}</p>
        <p>
        {{ post.created_at.strftime('%H:%M %Y-%m-%d') }} |
        {% with total=post.comments|length %}
            {{ total }} comment {%- if total > 1 %}s{%- endif -%}
        {% endwith %}
        </p>
    {% endfor %}
{% endblock %}

app/templates/unity/listUnity.html
{% extends "base.html" %}
{% from "macros.html" import render_pager with context %}
{% from "macros.html" import render_disqus_count with context %}

{% block content %}
    {% for item in unitySet.items %}
        <h2>
            <a href="{{ url_for('unity.staticUnity', slug=item.slug) }}">{{ item.title }}</a>
        </h2>
        {% if item.summary %}
            <p>{{item.summary|markRight|striptags}}</p>
        {% else %}
            <p>{{ item.body|markRight|striptags|truncate(100) }}</p>
        {% endif %}
        <p>by <a href="{{ url_for('users.profile', user_id=item.author.email) }}">{{item.author.email}}</a> | 
            {{ item.created_at.strftime('%H:%M %Y-%m-%d') }} | 
            <a href="{{ url_for('unity.staticUnity', slug=item.slug) }}#disqus_thread"></a>
           {#
           {% with total=item.comments|length %}
               {{ total }} comment {%- if total != 1 %}s{%- endif -%}
           {% endwith %}
           #}
        </p>
    {% endfor %}
    {{ render_pager(unitySet, 'unity.listUnity') }}
{% endblock %}
{% block footer %}
    {{ render_disqus_count() }}
{% endblock %}

app/templates/unity/newUnity.html
<!-- extends base.html -->
{% extends "base.html" %}
{% from "macros.html" import render_form with context %}
{% block head %}
    {{ pagedown.include_pagedown() }}
{% endblock %}

{% block content %}
    {{ render_form('newUnity') }}
{% endblock %}
{% block sidebar %}
    <div id="markdown-help">
        <h3>Markdown Cheatsheet</h3>
        <ul id="markdown-example">
            <li><i>_italic_</i></li>
            <li><b>**bold**</b></li>
            <li><i><b>***italic & bold***</b></i></li>
            <li>&lthttp://foo.com&gt</li>
            <li>[foo](http://foo.com)</li>
            <li>[[wikiLink]]</li>
            <li>![img](http://link/to)</li>
            <li>-----&lthr&gt</li>
            <li><h1>###h1</h1> or ===</li>
            <li><h2>###h2</h2> or ---</li>
            <li><h3>###h3</h3></li>
            <li>- list</li>
            <li>[5spaces]- list</li>
            <li>1. list</li>
            <li>[4spaces]A. list</li>
            <li>[4spaces]code</li>
            <li><pre>```code```</pre></li>
            <li><blockquote>>blockquote</blockquote></li>
        </ul>
    </div><!--end markdown-help-->
{% endblock %}

app/templates/unity/resume.html
<!-- extends base.html -->
{% extends "base.html" %}

{% block head %}
    <link rel="stylesheet/less" type="text/css" href="{{ url_for('static', filename='css/resume.less') }}" />
    <script src="http://cdnjs.cloudflare.com/ajax/libs/less.js/1.4.1/less.min.js" type="text/javascript"></script>
{% endblock %}

{% block content %}
<div id="resume">
<div id="resumeHeader">
    <h2 id="headerName">Cameron Dershem</h2>
    <div id="headerNotName">
        <script src="{{ url_for('static', filename='js/email_resume.js') }}">
            </script><span id="pipeseparator"> | </span>
        <a href="callto:312.361.0322">312.361.0322</a>
            <span id="pipeseparator"> | </span>
        Indianapolis, IN<br>
        <a href="{{ url_for('index')}}">homelessgaffer.com</a>
            <span id="pipeseparator"> | </span>
        <a href="http://github.com/cldershem">github.com/cldershem</a>
    </div><!--end headerNotName-->
</div><!--end resumeHeader-->
<hr class="resumeHR">
{# show if Dev #}
<div id="objective">
    <span class="sectionHeader" id="objectiveHeader"><h3>OBJECTIVE: </h3></span>
    To successfully transition careers into application development
    by obtaining an entry-level position to gain experience and
    knowledge.  Seeking new challenges and stability by
    leveraging an enthusiasm for efficiency and simplicity while
    finding and building solutions.
</div><!--end objective-->
<hr class="resumeHR">
{# endif #}
<div id="experience">
    <div class="sectionHeader">
        <h3>EXPERIENCE</h3>
    </div><!--sectionHeader-->
    <div class="jobHeader">
        <span class="jobName">MarketStar</span>
        <span class="location">Indianapolis, IN</span>
        <br>
        <span class="jobTitle">Google Specialist</span>
        <span class="dates">November 2012 &ndash; December 2012</span>
    </div><!--jobheader-->
    <ul class="jobDescription">
        <li>
            Educated guests on Google's ecosystem and products, focusing on the Google Chromebook
        </li>
	    <li>
            Answered questions involving Google and how it could better the guests' current needs
        </li>
        <li>
            Developed training methods for the continued education of colleagues
        </li>
        <li>
            Assisted guests with questions and issues&mdash;finding the answer even if it was not a Google product
        </li>
	    <li>
            Used, tested, troubleshot products, and reported bugs to the proper teams
        </li>
    </ul><!--end jobDescription-->
    <div class="jobHeader">
        <span class="jobName">Orange 20 Bikes</span>
        <span class="location">Los Angeles, CA</span>
        <br>
        <span class="jobTitle">IT Management &amp; Inventory Control</span>
        <span class="dates">October 2011 &ndash; June 2012</span>
    </div><!--jobheader-->
    <ul class="jobDescription">
	    <li>
            Designed and implemented improvements to POS and inventory control systems
        </li>
	    <li>
            Created systems to improve employee communications&mdash;greatly increasing efficiency and morale
        </li>
	    <li>
            Trained management and employees on best practices to reduce loss, save time, and save money
        </li>
    </ul><!--end jobDescription-->
    <div class="jobHeader">
        <span class="jobName">Camadeus Film Technologies, Inc</span>
        <span class="location">Los Angeles, CA</span>
        <br>
        <span class="jobTitle">Rental Agent</span>
        <span class="dates">June 2010 &ndash; September 2011</span>
    </div><!--jobheader-->
    <ul class="jobDescription">
	    <li>
            Implemented and maintained a new inventory control system&mdash;improving office and warehouse efficiency
        </li>
        <li>
            Organized and lead workshops and demonstrations to educate and train clients as well as employees
        </li>
	    <li>
            Maintained equipment regularly&mdash;troubleshooting, servicing, and reporting bugs as needed
        </li>
	    <li>
            Provided on call support by phone and on location&mdash;making sure the client could make their day 
        </li>
	    <li>
            Coordinated rentals from initial contact to delivery, invoicing, subrentals, returns, and follow ups
        </li>
    </ul><!--end jobDescription-->
    <div class="jobHeader">
        <span class="jobName">Various Motion Picture Productions</span>
        <span class="location">Chicago, IL &amp; Los Angeles, CA</span>
        <br>
        <span class="jobTitle">Freelance Gaffer &amp; Best Boy Electric</span>
        <span class="dates">June 2002 &ndash; June 2010</span>
    </div><!--jobheader-->
    <ul class="jobDescription">
	    <li>
            Controlled the look of a film through lighting techniques with direction from the Cinematographer%Director of Photography
        </li>
	    <li>
            Managed a department and crew ranging from 2&ndash;20&mdash;including personnel decisions, records, and budget
        </li>
	    <li>
            Appropriated, inventoried, serviced, and maintained equipment for the duration of the job
        </li>
	    <li>
            Analyzed electrical needs and distributed power appropriately&mdash;always keeping a safe and efficient set
        </li>
	    <li>
            Acted as liaison between the Lighting Department, Production, and all other departments
        </li>
    </ul><!--end jobDescription-->
    {# show if not Dev #}
    <div class="jobHeader">
        <span class="jobName">Columbia College Chicago</span>
        <span class="location">Chicago, IL</span>
        <br>
        <span class="jobTitle">Teacher's Assistant &amp; Projectionist</span>
        <span class="dates">August 2003 &ndash; June 2006</span>
    </div><!--jobheader-->
    <ul class="jobDescription">
        <li>
            Managed equipment rentals&mdash;including maintaining, troubleshooting, and servicing equipment as needed
        </li>
        <li>
            Answered questions from students and assisted teachers in better conveying class material
        </li>
        <li>
            Occasionally taught classes in teacher's absence
        </li>
	    <li>
            Projected film in 35mm, 16mm, and digital formats 
        </li>
    </ul><!--end jobDescription-->
    {# endif #}
</div><!--end experience-->
<hr class="resumeHR">
{# show if Dev #}
<div id="personalProjects">
    <div class="sectionHeader">
        <h3>PERSONAL &amp; PUBLIC PROJECTS</h3>
    </div><!--sectionHeader-->
    <dl id="projectList">
        <dt>Battleship &ndash;</dt>
        <dd>
            Multiplayer game written in Python&mdash;eventually to be rewritten as a web app
        </dd>
        <dt>HomelessGaffer.com &ndash;</dt>
        <dd>
            Simple CMS written in Python using Flask&mdash;deployed using git-hooks
        </dd>
    </dl>
</div><!--personalProjects-->
{# endif #}
<hr class="resumeHR">
<div id="education">
    <div class="sectionHeader">
        <h3>EDUCATION</h3>
    </div><!--sectionHeader-->
	<div class="jobHeader">
        <span class="jobName">Columbia College Chicago</span>
        <span class="location">Chicago, IL</span>
        <br>
        <span class="jobTitle">B.A. Film/Video &mdash; Cinematography Concentration</span>
        <span class="dates">2003 &ndash; 2008</span>
    </div><!--jobheader-->
</div><!--education-->
<hr class="resumeHR">
<div id="skills">
    <div class="sectionHeader">
        <h3>SKILLS &amp; INTERESTS</h3>
    </div><!--sectionHeader-->
    <div id="skillsmulticol">
        <ul id="skillsleftcol">
            <li>
                Adept in Linux, Windows, OS X, Chrome OS, Android
            </li>
            <li>
                Confident and comfortable with Python, Flask, HTML, CSS, LESS, JavaScript, <span class="latex">L<sup>a</sup>T<sub>e</sub>X</span>
            </li>
        	<li>
                Good understanding and capable of working with MySQL, MongoDB, PHP
            </li>
        	<li>
                Willingness and ability to learn new products and skills efficiently along with the patience to teach others
            </li>
        	<li>
                Strong troubleshooting skills&mdash;always focused on efficiency and finding solutions
            </li>
        	<li>
                Very capable of competently multitasking and able to keep up morale while doing just about anything
            </li>
        </ul>
        <ul id="skillsrightcol">
        	<li>
                Excellent communication skills&mdash;able to take direction as well as lead a team
            </li>
        	<li>
                Prefers Vim for editing, Git for versioning, and been an Ubuntu user since Hardy
            </li>
        	<li>
                Always reading about technologies, tinkering with gadgets, and an all around geek
            </li>
        	<li>
                Enjoys cooking and complete cast iron nerd
            </li>
        	<li>
                Passionate about cinema, cinematography, still photography&mdash;specifically lighting
            </li>
        	<li>
                Avid cyclist, wishful randonneur, and dedicated velodrome attendee
            </li>
            <li>
                Currently learning Java and attempting to learn Spanish (albeit, muy lentamente)
            </li>
        </ul>
    </div><!--end skillsmulticol-->
</div><!--end skills-->
</div><!--end resume-->
{% endblock %}
{% block sidebar %}
    <ul id="linklist">
        <li>
            <a href="http://docs.google.com">view pdf</a>
        </li>
        <li>
            <a href="http://docs.google.com">download pdf</a>
        </li>
    </ul>
{% endblock %}

app/templates/unity/staticUnity.html
<!-- extends base.html -->
{% extends "base.html" %}
{% from "macros.html" import render_form with context %}
{% from "macros.html" import render_comments with context %}
{% from "macros.html" import render_disqus with context %}

{% block content %}
{{unity.body|markRight}}
<hr>
<div id="postmeta">
    <p>
        by <strong><a href="{{ url_for('users.profile', user_id=unity.author.email) }}">{{ unity.author.email }}</a></strong>
        <span id="pipeseparator"> | </span>posted {{ unity.created_at.strftime('%H:%M %Y-%m-%d') }}
        {% if unity.edited_on|length > 1 %}
            <span id="pipeseparator"> | </span>edited {{ unity.edited_on[-1].strftime('%H:%M %Y-%m-%d') }}
        {% endif %}
    </p>
    {% if unity.tags %}
        <p>
            <strong>tags: </strong>
            {% for tag in unity.tags %}
                [<a class="unitytags" href="{{ url_for('unity.listUnity', tag=tag) }}">{{tag}}</a>]
            {% endfor %}
        </p>
    {% endif %}
    {% if unity.source %}
        <p>
            <strong>source: </strong>
            {% for source in unity.source %}
            [<a href="{{ source }}" title="{{ source }}">{{ source }}</a>]
            {% endfor %}
        </p>
    {% endif %}
    {% if current_user.is_authenticated() == True %}
        <p>
            <a href="{{url_for('unity.editUnity', slug=unity.slug)}}">edit page</a>
        </p>
    {% endif %}
</div><!--end postmeta-->
{#{render_comments(unity.comments)}#}
{{render_disqus()}}
{% endblock %}

app/templates/unity/work.html
<!-- extends base.html -->
{% extends "base.html" %}

{% block content %}
<p>stuff goes here</p>
{% endblock %}