app/unity/views.py
from flask import (Blueprint, render_template, flash, request,
                   redirect, url_for)
from jinja2 import TemplateNotFound
from app.models import Unity, User, Comment
from app.forms import UnityForm, CommentForm
from app.constants import DATE_TIME_NOW
from app.utils import makeSlug
from flask.ext.login import login_required, current_user
from flask.ext.mongoengine import Pagination

mod = Blueprint('unity', __name__, url_prefix='/unity')


@mod.route('/', defaults={'tag': None, 'user': None, 'pageNum': 1})
@mod.route('/blog', defaults={'tag': None, 'user': None, 'pageNum': 1})
@mod.route('/listposts', defaults={'tag': None, 'user': None, 'pageNum': 1})
@mod.route('/listposts/page/<int:pageNum>',
           defaults={'tag': None, 'user': None})
@mod.route('/listposts/tag/<tag>', defaults={'user': None, 'pageNum': 1})
@mod.route('/listposts/tag/<tag>/page/<int:pageNum>', defaults={'user': None})
@mod.route('/listposts/user/<user>', defaults={'tag': None, 'pageNum': 1})
@mod.route('/listposts/user/<user>/page/<int:pageNum>', defaults={'tag': None})
def listUnity(tag, user, pageNum):
    if tag:
        unitySet = Pagination(
            Unity.get_set(postType='blog', tags=tag),
            pageNum, 10)
        pageTitle = tag
    if user:
        user = User.get(email=user)
        unitySet = Pagination(
            Unity.get_set(postType='blog', author=user),
            pageNum, 10)
        pageTitle = user.email
    elif not tag and not user:
        unitySet = Pagination(
            Unity.get_set(postType='blog'),
            pageNum, 10)
        pageTitle = "blog"  # "listUnity"
    return render_template('unity/listUnity.html',
                           pageTitle=pageTitle,
                           unitySet=unitySet,
                           page=pageNum)


@mod.route('/newunity', methods=['GET', 'POST'])
@login_required
def newUnity():
    form = UnityForm()

    if request.method == 'POST':
        if not form.validate_with_slug():
            return render_template("unity/newUnity.html",
                                   form=form,
                                   pageTitle="newUnity")
        else:
            slug = makeSlug(form.title.data)
            newUnity = Unity(title=form.title.data,
                             slug=slug,
                             body=form.body.data,
                             postType=form.postType.data)
            if form.tags.data:
                newUnity.tags = form.tags.data
            if form.source.data:
                newUnity.source = form.source.data
            if form.summary.data:
                newUnity.summary = form.summary.data
            newUnity.author = User.get(email=current_user.email)
            newUnity.save()
            flash('Your unity has been posted.')
            return redirect(url_for('.staticUnity', slug=slug))
    elif request.method == 'GET':
        return render_template("unity/newUnity.html",
                               form=form,
                               pageTitle="newUnity")


@mod.route('/<slug>/edit', methods=['GET', 'POST'])
@login_required
def editUnity(slug):
    unity = Unity.get(slug=slug)
    slug = unity.slug
    form = UnityForm(obj=unity)

    if request.method == 'POST':
        if not form.validate_on_update(slug):
            return render_template('unity/newUnity.html',
                                   pageTitle=unity.title,
                                   slug=slug,
                                   form=form)
        else:
            form.populate_obj(unity)
            unity.edited_on.append(DATE_TIME_NOW)
            unity.save()
            flash("Your page has been updated.")
            return redirect(url_for('.staticUnity', slug=slug))
    elif request.method == 'GET':
        form.populate_obj(unity)
        return render_template('unity/newUnity.html',
                               pageTitle=unity.title,
                               slug=slug,
                               form=form)


@mod.route('/<slug>', methods=['GET', 'POST'])
def staticUnity(slug):
    if request.method == 'POST':
        unity = Unity.get_or_404(slug=slug)
        form = CommentForm()
        if not form.validate():
            return render_template('unity/staticUnity.html',
                                   pageTitle=unity.title,
                                   unity=unity,
                                   form=form)
        else:
            newComment = Comment(body=form.comment.data)
            newComment.author = User.get(email=current_user.email)
            unity.comments.append(newComment)
            unity.save()
            form.comment.data = None  # resets field on refresh
            flash('Comment Posted')
        return render_template('unity/staticUnity.html',
                               pageTitle=unity.title,
                               unity=unity,
                               form=form)
    elif request.method == 'GET':
        try:
            return render_template('unity/%s.html' % slug,
                                   pageTitle=slug)
        except TemplateNotFound:
            unity = Unity.get_or_404(slug=slug)
            currentUser = User.get(email=current_user.email)
            if (unity.postType == 'draft' and
                    unity.author != currentUser and
                    currentUser.is_admin() is False):
                flash('You must be draft author or admin to view.')
                return redirect(url_for('.listUnity'))
            else:
                form = CommentForm()
                return render_template('unity/staticUnity.html',
                                       pageTitle=unity.title,
                                       unity=unity,
                                       form=form)

app/users/views.py
from flask import (Blueprint, render_template, url_for, request,
                   redirect, flash, g, abort, session)
from app import lm
from app.forms import (LoginForm, RegisterUser,
                       ForgotPasswordForm, ResetPasswordForm)
from app.models import (User)
from flask.ext.login import (login_user, logout_user,
                             current_user, login_required)
from app.constants import DATE_TIME_NOW
from app.emails import email_confirmation, email_password_reset
from app.decorators import anon_required


mod = Blueprint('users', __name__, url_prefix='/users')


@lm.user_loader
def load_user(id):
    user = User.get(email=id)
    return user


@mod.before_request
def before_request():
    g.user = current_user


@mod.route('/login', methods=['GET', 'POST'])
@anon_required
def login():
    form = LoginForm()
    pageTitle = "login"

    if request.method == 'POST':
        if form.validate() is False:
            return render_template('users/login.html',
                                   form=form,
                                   pageTitle=pageTitle)
        else:
            # user = User.get(email=form.email.data.lower().strip())
            user = User.get(email=form.email.data.lower().strip())
            if user and user.roles.can_login is True:
                #add remember_me
                user.last_seen = DATE_TIME_NOW
                user.save()
                login_user(user)
                return redirect(request.args.get('next') or
                                url_for('.profile',
                                        user_id=user.get_id())
                                )
            else:
                flash("Please confirm your email address.")
                return render_template('users/login.html',
                                       form=form,
                                       pageTitle=pageTitle)
    elif request.method == 'GET':
        if request.args.get('next'):
            session['next'] = (request.args.get('next') or
                               request.referrer or None)
        return render_template('users/login.html',
                               form=form,
                               pageTitle=pageTitle)


def after_login(resp):
    pass


@mod.route('/logout')
@login_required
def logout():
    logout_user()
    if session.get('credentials'):
        if redirect(url_for('.googleDisconnect')):
            flash("Successfully disconnected from Google.")
    flash("Successfully logged out.")
    session.clear()
    return redirect(url_for('index'))


@mod.route('/register', methods=['GET', 'POST'])
@anon_required
def register():
    form = RegisterUser()
    pageTitle = "register"

    if request.method == 'POST':
        if form.validate() is False:
            return render_template('users/register.html',
                                   form=form,
                                   pageTitle=pageTitle)
        else:
            newUser = User(firstname=form.firstname.data.title(),
                           lastname=form.lastname.data.title(),
                           email=form.email.data.lower().strip())
            newUser.set_password(form.password.data)
            newUser.save()
            payload = User.get_activation_link(newUser)
            email_confirmation(newUser, payload)
            flash("Please confirm your email address by cheking your email.")
            return redirect(url_for('index'))

    elif request.method == 'GET':
        return render_template('users/register.html',
                               form=form,
                               pageTitle=pageTitle)

    # flash("This feature is currently disabled.")
    # return redirect(url_for('index'))


@mod.route('/activate/<payload>')
@anon_required
def activateUser(payload):
    user_email = User.check_activation_link(payload)
    if not user_email:
        return abort(404)
    user = User.get(email=user_email)
    if user:
        if user.confirmed is None:
            user.activate_user()
            user.save()
            flash('Your account has been activated.')
        else:
            flash('Your account was already active.')
        return redirect(url_for('.login'))
    else:
        return abort(404)


@mod.route('/forgotpassword', methods=['GET', 'POST'])
@anon_required
def forgotPassword():
    form = ForgotPasswordForm()
    pageTitle = "forgot password"

    if request.method == 'POST':
        if not form.validate():
            return render_template('users/forgotPassword.html',
                                   form=form,
                                   pageTitle=pageTitle)
        else:
            try:
                user = User.get(email=form.email.data.lower().strip())
            except:
                flash("That email does not exist, please try another.")
                return render_template('users/forgotPassword.html',
                                       form=form,
                                       pageTitle=pageTitle)

            # # disallows password reset link to be reused
            # oldhash = user.pwdhash[:10]
            # payload = User.get_password_reset_link(user) + oldhash

            payload = User.get_password_reset_link(user)
            email_password_reset(user, payload)

            flash("Password reset email has been sent. \
                   Link is good for 24 hours.")
            return redirect(url_for('index'))
    elif request.method == 'GET':
        return render_template('users/forgotPassword.html',
                               form=form,
                               pageTitle="Forgot Password")


@mod.route('/resetpassword/<payload>', methods=['GET', 'POST'])
@anon_required
def reset_password(payload):
    form = ResetPasswordForm()
    pageTitle = "reset password"

    # disallows password reset link to be reused
    unhashed_payload = User.check_password_reset_link(payload)
    user_email = unhashed_payload[0]
    oldhash = unhashed_payload[1]

    if user_email:
        user_oldhash = User.get(email=user_email).pwdhash[:10]
        if oldhash != user_oldhash:
            flash("Token has been used previously.  Please try again.")
            return redirect(url_for('.forgotPassword'))

    if not user_email:
        flash("Token incorrect or has expired.  Please try again.")
        return redirect(url_for('.forgotPassword'))

    if request.method == 'POST':
        if not form.validate():
            return render_template('users/resetPassword.html',
                                   form=form,
                                   pageTitle=pageTitle)
        else:
            user = User.get(email=user_email)
            user.set_password(form.password.data)
            user.save()
            #email password reset
            flash("Password has been reset, please login")
            return redirect(url_for('.login'))
    elif request.method == 'GET':
        return render_template('users/resetPassword.html',
                               form=form,
                               pageTitle=pageTitle)


@mod.route('/profile/<user_id>')
def profile(user_id):
    user = User.get(email=user_id)
    return render_template('users/profile.html',
                           user=user,
                           pageTitle=user_id)

app/templates/base.html
<!DOCTYPE HTML>
<html>
    <head>
        <title>hg-{% block title %}{{pageTitle}}{% endblock %}</title>
        <link rel="stylesheet/less" type="text/css" href="{{ url_for('static', filename='css/style.less') }}" />
        <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.png') }}">
        <script src="http://cdnjs.cloudflare.com/ajax/libs/less.js/1.4.1/less.min.js" type="text/javascript"></script>
        {% block head %}{% endblock %}
        {% from 'macros.html' import render_navbar %}
        <script>
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

          ga('create', 'UA-11888561-1', 'homelessgaffer.com');
          ga('send', 'pageview');

        </script>
    </head>
    <body>
        <div id="bigOwrapper">
            <header>
                <nav>
                    <a id="hgtitle" href="/index"><span id="tilde">~/</span>hg/</a>
                    <ul>
                        <li class="topmenu">
                            <a {%- if pageTitle == 'blog' %} class="currentpage" {% endif %} href="/unity/blog">blog</a>
                            <ul class="submenu">
                                <li>
                                    <a {%- if pageTitle == 'food' %} class="currentpage" {% endif %} href="/unity/listposts/tag/food">food</a>
                                </li>
                                <li>
                                    <a {%- if pageTitle == 'bike' %} class="currentpage" {% endif %} href="/unity/listposts/tag/bike">bike</a>
                                </li>
                            </ul>
                        </li>
                        <li class="topmenu">
                            <a {%- if pageTitle == 'dev' %} class="currentpage" {% endif %} href="/unity/dev">dev</a>
                            <ul class="submenu">
                                <li>
                                    <a {%- if pageTitle == 'battleship' %} class="currentpage" {% endif %} href="/unity/battleship">battleship</a>
                                </li>
                            </ul>
                        </li>
                        <li class="topmenu">
                            <a {%- if pageTitle == 'about' %} class="currentpage" {% endif %} href="/unity/about">about</a>
                            <ul class="submenu">
                                <li>
                                    <a {%- if pageTitle == 'resume' %} class="currentpage" {% endif %} href="/unity/resume">resume</a>
                                </li>
                                <li>
                                    <a {%- if pageTitle == 'contact' %} class="currentpage" {% endif %} href="/unity/contact">contact</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </nav>
            </header>
            <div id="allNonHeader">
                <div id="pageTitle">
                    <h1>{{pageTitle or "UPDATE ME!!!!"}}</h1>
                </div>
                <div id="leftcontent">
                    <div id="flashMessage">
                        {%- with messages = get_flashed_messages() -%}
                            {%- if messages -%}
                                <ul>
                                    {%- for message in messages -%}
                                        <li>{{ message }}</li>
                                    {%- endfor %}
                                </ul>
                            {% endif %}
                        {% endwith %}
                    </div>
                {% block content %}
                {% endblock %}
                </div><!--end leftcontent-->
                <div id="sidebar">
                    {% block sidebar %}
                    {% endblock %}
                </div><!--end sidebar-->
            <footer>
                <p>
                    this is the footer to this page.  it is copycentered.
                </p>
                {% block footer %}
                {% endblock %}
            </footer>
            </div><!--end allNonheader-->
        </div><!--end #bigOwrapper-->
    </body>
</html>

app/templates/dev.html
<!-- extends base.html -->
{% extends "base.html" %}
{% block title %}dev{% endblock %}
{% set page = 'dev' %}

{% block content %}
<table id="contactinfo">
	<tr>
		<th><a href="http://homelessgaffer.com/wikitest/tikiwiki">wiki</a></th><td>wiki about bicycle tour</td>
	</tr>
	<tr>
		<th><a href="{{ url_for('battleship') }}">battleshipWeb</a></th><td>first medium python game turned into a lesson in javascript, kinetic.js, and canvas.</td>
	</tr>
	<tr>
		<th>genealogy</th><td>million dollar idea</td>
	</tr>
	<tr>
		<th>firstkisses</th><td>first kisses project</td>
	</tr>
</table>
{% endblock %}

app/templates/error404.html
<!-- extends base.html -->
{% extends "base.html" %}

{% block content %}
    <h2>404</h2>
    <h3>Page not found.</h3>
    <p>
        One of us screwed up....probably me, but I'm gonna keep my eye on you.
    </p>
{% endblock %}

app/templates/error500.html
<!-- extends base.html -->
{% extends "base.html" %}

{% block content %}
    <h3>Internal server error.</h3>
    <p>
        One of us screwed up....probably me, but I'm gonna keep my eye on you.
    </p>
{% endblock %}

app/templates/index.html
<!-- extends base.html -->
{% extends "base.html" %}

{% block content %}
		<p>
			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec justo massa,
			condimentum a rutrum a, sollicitudin ut quam. Phasellus dictum velit vel lorem
			feugiat fringilla. Aliquam erat volutpat. Sed eu ligula neque. Vestibulum
			condimentum lobortis nisl ut pharetra. Fusce facilisis elit ut nibh tristique at
			dictum turpis bibendum. Proin luctus porttitor pretium. Etiam vitae nulla urna,
			luctus iaculis magna. Curabitur nunc augue, accumsan sed suscipit et, viverra congue
			sem. Phasellus interdum magna eu mi euismod pretium. Quisque in vestibulum tortor.
			Aenean laoreet est sed purus ultrices feugiat. Maecenas dui nunc, tincidunt ut mollis
			quis, mollis nec lorem. Curabitur in mauris ante. Nunc iaculis posuere arcu eget
			luctus. Aenean pulvinar facilisis arcu, quis egestas nulla venenatis in.
			Pellentesque vitae luctus nulla. Duis quam libero, interdum egestas pharetra
			vel, tempor nec turpis. Sed mauris tortor, auctor ut ultricies sed, lacinia quis mi.
			<a href="http://google.com">this is a link</a>
		</p>
{% endblock %}

app/templates/listPosts.html
{% extends "base.html" %}

{% block title %}{{title}}{% endblock %}
{% set page = title %}

{% block content %}
    {% for post in posts.items %}
        <h2><a href="{{ url_for('singlePost', slug=post.slug) }}">{{ post.title }}</a></h2>
        <p>{{ post.body|striptags|truncate(100) }}</p>
        <p>
            by <a href="{{ url_for('profile', user=post.author.email) }}">{{post.author.email}}</a> | 
        {{ post.created_at.strftime('%H:%M %Y-%m-%d') }} |
        {% with total=post.comments|length %}
            {{ total }} comment {%- if total > 1 %}s{%- endif -%}
        {% endwith %}
        </p>
    {% endfor %}
    <div id="pagination">
    {% if posts.has_prev %}
        <a href="{{url_for('listPosts', page=posts.prev_num)}}">newer</a>
    {% endif %}
    {% for page in posts.iter_pages() %}
        {% if page %}
            {% if page == 1 and posts.has_next == False %} <!-- if only page, don't show pages-->
            {% elif page != posts.page %}
                <a href="{{url_for('listPosts', page=page)}}">{{page}}</strong></a>
            {% else %}
                <strong>{{page}}</strong>
            {% endif %}
        {% else %}
            <p>else again </p>
        {% endif %}
    {% endfor %}
    {% if posts.has_next %}
        <a href="{{url_for('listPosts', page=posts.next_num)}}">older</a>
    {% endif %} 
    </div> <!--pagination-->
{% endblock %}

app/templates/login.html
<!-- extends base.html -->
{% extends "base.html" %}
{% block title %}login{% endblock %}
{% set page = 'login' %}

{% block content %}
<form id="login" action="" method="post">
    {{form.hidden_tag()}}
    <table>
        <tr>
            <td>{{form.email.label}}:</td>
            <td>{{form.email(size=10)}}</td>
            {% for error in form.errors.email %}
                <td>
                    [{{error}}]
                </td>
            {% endfor %}
        </tr>
        <tr>
            <td>{{form.password.label}}:</td>
            <td>{{form.password(size=10)}}</td>
            {% for error in form.errors.password %}
                <td>
                    [{{error}}]
                </td>
            {% endfor %}
        </tr>
        <tr>
            <td>{{form.remember_me.label}}:</td>
            <td>{{form.remember_me(size=10)}}</td>
            {% for error in form.errors.remember_me %}
                <td>
                    [{{error}}]
                </td>
            {% endfor %}
        </tr>
        <tr>
            <td></td>
            <td>{{form.submit}}</td>
        </tr>
        <tr>
            <td></td>
            <td>or <a href="{{ url_for('register') }}">register</a></td>
        </tr>
        <tr>
            <td></td>
            <td>or <a href="{{ url_for('forgotPassword') }}">Forgot Password</a></td>
        </tr>
    </table>
</form>
{% endblock %}

app/templates/macros.html
{% macro render_form(formID) %}
    <form id={{formID}} action="" method="post">
    {{form.hidden_tag()}}
        {%  for field in form if field.widget.input_type != 'hidden' %}
            {% if field.type == 'TextField' or
                field.type == 'PageDownField' or
                field.type == 'TextAreaField' %}
                {{field.label}}
                    {% for error in field.errors %}
                        <span class="formError">
                            [{{error}}]
                        </span>
                    {% endfor %}</br >
                {% if field.id == 'body' or field.id == 'content' %}
                    {{field(rows=20,cols=40)}}
                {% else %}
                    {{field}}
                {% endif %}</br>
            {% elif field.id == 'submit' %}
                {{field}}</br>
            {% else %}
                {{field.label}}
                {{field}}</br>
            {% endif %}
        {% endfor %}
    </form>
{% endmacro %}

{% macro render_pager(pageSet, endpoint) %}
    <div id="pagination">
        {% if pageSet.has_prev %}
            <a href="{{url_for(endpoint, pageNum=pageSet.prev_num)}}">newer</a>
        {% endif %}
        {% for page in pageSet.iter_pages() %}
            {% if pageSet.page == 1 and not pageSet.has_next %} <!-- dont show if only page -->
            {% else %}
                {% if page == pageSet.page %}
                    {{page}}
                {% else %}
                    <a href="{{url_for(endpoint, pageNum=page)}}">{{page}}</strong></a>
                {% endif %}
            {% endif %}
        {% endfor %}
        {% if pageSet.has_next %}
            <a href="{{url_for(endpoint, pageNum=pageSet.next_num)}}">older</a>
        {% endif %} 
    </div><!--pagination-->
{% endmacro %}

{% macro render_comments(commentSet) %}
    <div id="comments">
        <h2 id="commentHeader">Comments</h2>
        {% if commentSet %}
            {% for comment in commentSet %}
                <p class="commentbody">{{ comment.body }}</p>
                <p id="commentmeta">by <strong>{{ comment.author.get_id() }}</strong> on {{ comment.created_at.strftime('%H:%M %Y-%m-%d') }}</p>
                <hr>
            {% endfor %}
        {% endif %}
        {% if current_user.is_authenticated() == True -%}
            <h2>Add a comment</h2>
                {{ render_form('addComment') }}
        {% else %}
            <p><a href="{{url_for('users.login')}}">login</a> to comment.</p>
        {% endif %}
    </div><!--end comments-->
{% endmacro %}

{% macro render_disqus() %}
    <div id="disqus_thread"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = '{{config.DISQUS_SHORTNAME}}'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
{% endmacro %}

{% macro render_disqus_count() %}
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = '{{config.DISQUS_SHORTNAME}}'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function () {
            var s = document.createElement('script'); s.async = true;
            s.type = 'text/javascript';
            s.src = '//' + disqus_shortname + '.disqus.com/count.js';
            (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
        }());
    </script>
{% endmacro %}

{%- macro render_navbar(pageTitle, type, arg) %}
    <li {%- if pageTitle == arg %} class="currentpage" {% endif %}>
    {%- if type == 'slug' -%}
        <a href="{{url_for('unity.staticUnity', slug=arg)}}">{{arg}}</a>
    {%- elif type == 'tag' -%}
        <a href="{{url_for('unity.listUnity', tag=arg)}}">{{arg}}</a>
    {%- endif -%}
{% endmacro -%}

app/templates/newPage.html
<!-- extends base.html -->
{% extends "base.html" %}
{% block head %}
<script src="{{url_for('static', filename='js/ckeditor/ckeditor.js') }}" type="text/javascript"></script>
{% endblock %}
{% block title %}newpage{% endblock %}
{% set page = 'newpage' %}
{% set headerImg = url_for('static', filename='img/babytenor-400x67.jpg') %}

{% block content %}
<form id="newpage" action="" method="post">
    {{form.hidden_tag()}}
    <table>
        <tr>
            <td>{{form.title.label}}:</td>
            <td>{{form.title(size=10)}}</td>
            {% for error in form.errors.title%}
                <td>
                    [{{error}}]
                </td>
            {% endfor %}
        </tr>
        <tr>
            <td>{{form.content.label}}:</td>
            <td>{{form.content(size=10)}}</td>
            {% for error in form.errors.content %}
                <td>
                    [{{error}}]
                </td>
            {% endfor %}
        </tr>
        <tr>
            <td></td>
            <td>{{form.submit}}</td>
        </tr>
    </table>
</form>
{% endblock %}

app/templates/singlePost.html
{% extends "base.html" %}
{% block title %}{{post.title}}{% endblock %}
{% set page=post.title %}
{% block content %}
    <p>{{ post.body|safe }}</p>
    {% if post.tags %}
    <p>
        <strong>tags:</strong>
		{% for tag in post.tags %}
			<a class="posttags" href="{{ url_for('listPosts', tag=tag) }}">[{{tag}}]</a>
		{% endfor %}
    </p>
	{% endif %}
    <p>by <strong><a href="{{ url_for('profile', user=post.author.email) }}">{{ post.author.email }}</a></strong></p>
    <p>{{ post.created_at.strftime('%H:%M %Y-%m-%d') }}</p>
    <hr>
    <h2>Comments</h2>
    {% if post.comments %}
        {% for comment in post.comments %}
            <p>{{ comment.body }}</p>
            <p>by <strong>{{ comment.author.email }}</strong> <small>on {{ comment.created_at.strftime('%H:%M %Y-%m-%d') }}</small></p>
            {{ comment.text }}
        {% endfor %}
    {% endif %}
    <hr>
	{% if current_user.is_authenticated() == True -%}
		<h2>Add a comment</h2>
		<form id="addComment" action="" method="post">
			{{form.hidden_tag()}}
			<table>
				<tr>
					<td>{{form.comment.label}}:</td>
					<td>{{form.comment}}</td>
					{% for error in form.errors.comment %}
						<td>
							[{{error}}]
						</td>
					{% endfor %}
				</tr>
				<tr>
					<td></td>
					<td>{{form.submit}}</td>
				</tr>
			</table>
		</form>
	{% else %}
		<p><a href="{{url_for('login')}}">login</a> to comment.</p>
	{% endif %}
{% endblock %}